import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';

const TermsOfService = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-4xl mx-auto px-4 py-8">
        <Button
          variant="ghost"
          onClick={() => navigate(-1)}
          className="mb-6"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back
        </Button>

        <div className="bg-card rounded-lg border shadow-sm p-6 md:p-8">
          <h1 className="text-2xl md:text-3xl font-bold text-foreground mb-2">
            PredLabs - Terms and Conditions
          </h1>
          <h2 className="text-lg md:text-xl text-muted-foreground mb-6">
            For AI Medical Report Interpretation Service
          </h2>
          
          <p className="text-sm text-muted-foreground mb-8">
            Last Updated: 25/12/2025
          </p>

          <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-4 mb-8">
            <p className="text-sm font-medium text-destructive">
              PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY. BY ACCESSING OR USING OUR AI MEDICAL REPORT 
              INTERPRETATION SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND 
              BY THESE TERMS. IF YOU DO NOT AGREE, DO NOT USE THIS SERVICE.
            </p>
          </div>

          <div className="space-y-8 text-foreground">
            {/* Section 1 */}
            <section>
              <h3 className="text-xl font-semibold mb-4">1. Nature of the Service</h3>
              
              <div className="space-y-4 pl-4">
                <div>
                  <h4 className="font-medium mb-2">1.1 Informational Purpose Only</h4>
                  <p className="text-muted-foreground">
                    The AI-powered medical report interpretation provided by PredLabs ("the Service") is 
                    intended solely for general informational and educational purposes. The Service analyzes 
                    user-uploaded laboratory reports and presents an interpretation generated by artificial 
                    intelligence algorithms.
                  </p>
                </div>

                <div>
                  <h4 className="font-medium mb-2">1.2 Not a Healthcare Provider</h4>
                  <p className="text-muted-foreground">
                    PredLabs is not a licensed healthcare provider, medical institution, diagnostic laboratory, 
                    or clinical facility. We do not practice medicine, provide medical consultations, or 
                    establish any form of patient-physician or patient-healthcare provider relationship 
                    with our users.
                  </p>
                </div>
              </div>
            </section>

            {/* Section 2 */}
            <section>
              <h3 className="text-xl font-semibold mb-4">2. Critical Disclaimers - No Medical Advice or Diagnosis</h3>
              
              <div className="space-y-4 pl-4">
                <div className="bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-lg p-4">
                  <h4 className="font-medium mb-2 text-amber-800 dark:text-amber-200">2.1 Not a Substitute for Professional Medical Advice</h4>
                  <p className="text-amber-700 dark:text-amber-300">
                    The interpretations, summaries, and insights provided by the Service are NOT a substitute 
                    for professional medical advice, diagnosis, or treatment. You should NEVER disregard 
                    professional medical advice or delay seeking it based on any information or interpretation 
                    provided by this Service.
                  </p>
                </div>

                <div className="bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-lg p-4">
                  <h4 className="font-medium mb-2 text-amber-800 dark:text-amber-200">2.2 No Diagnosis or Prescription</h4>
                  <p className="text-amber-700 dark:text-amber-300">
                    The Service does NOT diagnose, treat, cure, or prevent any disease or health condition. 
                    The AI-generated interpretation does NOT constitute a medical diagnosis or a prescription 
                    for medication or any therapeutic intervention.
                  </p>
                </div>

                <div className="bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-lg p-4">
                  <h4 className="font-medium mb-2 text-amber-800 dark:text-amber-200">2.3 Consult a Qualified Healthcare Professional</h4>
                  <p className="text-amber-700 dark:text-amber-300">
                    For any health concerns, questions about your medical reports, or before making any 
                    health-related decisions, you MUST consult with a qualified and licensed physician, 
                    pathologist, or other appropriate healthcare professional.
                  </p>
                </div>
              </div>
            </section>

            {/* Section 3 */}
            <section>
              <h3 className="text-xl font-semibold mb-4">3. Accuracy Disclaimer & "As Is" Basis</h3>
              
              <div className="space-y-4 pl-4">
                <div>
                  <h4 className="font-medium mb-2">3.1 No Guarantee of Accuracy</h4>
                  <p className="text-muted-foreground">
                    While we strive for accuracy, PredLabs makes NO REPRESENTATIONS OR WARRANTIES of any 
                    kind, express or implied, regarding the accuracy, completeness, reliability, suitability, 
                    or timeliness of the AI-generated interpretations. AI technology, by its nature, can 
                    produce errors, omissions, or misinterpretations.
                  </p>
                </div>

                <div>
                  <h4 className="font-medium mb-2">3.2 Service Provided "As Is"</h4>
                  <p className="text-muted-foreground">
                    The Service is provided on an "AS IS" and "AS AVAILABLE" basis without any warranties 
                    of any kind. We expressly disclaim all implied warranties, including but not limited 
                    to implied warranties of merchantability, fitness for a particular purpose, and 
                    non-infringement.
                  </p>
                </div>

                <div>
                  <h4 className="font-medium mb-2">3.3 User Responsibility for Verification</h4>
                  <p className="text-muted-foreground">
                    It is entirely YOUR responsibility to verify ANY information or interpretation 
                    provided by the Service with a qualified healthcare professional before taking 
                    any action or making any decision based on such information.
                  </p>
                </div>
              </div>
            </section>

            {/* Section 4 */}
            <section>
              <h3 className="text-xl font-semibold mb-4">4. Absolute Limitation of Liability & Indemnification</h3>
              
              <div className="space-y-4 pl-4">
                <div className="bg-destructive/5 border border-destructive/20 rounded-lg p-4">
                  <h4 className="font-medium mb-2">4.1 No Liability for Damages</h4>
                  <p className="text-muted-foreground">
                    TO THE FULLEST EXTENT PERMITTED BY LAW, PREDLABS, ITS AFFILIATES, OFFICERS, DIRECTORS, 
                    EMPLOYEES, AGENTS, AND LICENSORS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
                    SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES ARISING OUT OF OR IN ANY WAY 
                    CONNECTED WITH YOUR USE OF OR INABILITY TO USE THE SERVICE. This includes, but is not 
                    limited to, damages for loss of profits, goodwill, use, data, or other intangible losses, 
                    personal injury, emotional distress, or any health-related outcomes.
                  </p>
                </div>

                <div>
                  <h4 className="font-medium mb-2">4.2 User Assumption of Risk</h4>
                  <p className="text-muted-foreground">
                    You expressly acknowledge and agree that your use of the Service is at your sole risk. 
                    You assume full responsibility for any outcomes, decisions, or actions taken based on 
                    the information provided by the Service.
                  </p>
                </div>

                <div>
                  <h4 className="font-medium mb-2">4.3 Indemnification</h4>
                  <p className="text-muted-foreground">
                    You agree to indemnify, defend, and hold harmless PredLabs and its affiliates, officers, 
                    directors, employees, agents, and licensors from and against any and all claims, liabilities, 
                    damages, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising 
                    from your use of the Service or your violation of these Terms.
                  </p>
                </div>
              </div>
            </section>

            {/* Section 5 */}
            <section>
              <h3 className="text-xl font-semibold mb-4 text-destructive">5. Prohibition on Legal & Regulatory Use</h3>
              
              <div className="space-y-4 pl-4">
                <div className="bg-destructive/10 border border-destructive/30 rounded-lg p-4">
                  <h4 className="font-medium mb-2 text-destructive">5.1 Not a Medicolegal Document</h4>
                  <p className="text-destructive/80">
                    THE INTERPRETATIONS AND REPORTS GENERATED BY THIS SERVICE ARE EXPLICITLY NOT INTENDED 
                    AND SHALL NOT BE USED AS MEDICOLEGAL DOCUMENTS. They cannot and should not be submitted 
                    or relied upon as evidence, proof, or official documentation in any legal, judicial, 
                    administrative, or regulatory proceeding.
                  </p>
                </div>

                <div className="bg-destructive/10 border border-destructive/30 rounded-lg p-4">
                  <h4 className="font-medium mb-2 text-destructive">5.2 No Use in Legal Proceedings</h4>
                  <p className="text-destructive/80">
                    You expressly agree NOT to use any output from this Service in connection with any 
                    court case, tribunal, arbitration, insurance claim, disability determination, 
                    employment dispute, medical malpractice claim, or any other legal or quasi-legal matter.
                  </p>
                </div>

                <div className="bg-destructive/10 border border-destructive/30 rounded-lg p-4">
                  <h4 className="font-medium mb-2 text-destructive">5.3 No Certification or Official Validation</h4>
                  <p className="text-destructive/80">
                    The Service does not provide certified, validated, or officially recognized medical 
                    interpretations. Our AI-generated content does not carry any professional medical 
                    certification, laboratory accreditation, or legal standing.
                  </p>
                </div>
              </div>
            </section>

            {/* Section 6 */}
            <section>
              <h3 className="text-xl font-semibold mb-4">6. General Provisions</h3>
              
              <div className="space-y-4 pl-4">
                <div>
                  <h4 className="font-medium mb-2">6.1 Modification of Terms</h4>
                  <p className="text-muted-foreground">
                    PredLabs reserves the right to modify these Terms at any time. We will notify users 
                    of significant changes. Your continued use of the Service after any modifications 
                    indicates your acceptance of the updated Terms.
                  </p>
                </div>

                <div>
                  <h4 className="font-medium mb-2">6.2 Governing Law</h4>
                  <p className="text-muted-foreground">
                    These Terms shall be governed by and construed in accordance with the laws of India, 
                    without regard to its conflict of law principles. Any disputes arising under these 
                    Terms shall be subject to the exclusive jurisdiction of the courts located in India.
                  </p>
                </div>

                <div>
                  <h4 className="font-medium mb-2">6.3 Severability</h4>
                  <p className="text-muted-foreground">
                    If any provision of these Terms is found to be unenforceable or invalid, that 
                    provision shall be limited or eliminated to the minimum extent necessary, and 
                    the remaining provisions shall remain in full force and effect.
                  </p>
                </div>

                <div>
                  <h4 className="font-medium mb-2">6.4 Entire Agreement</h4>
                  <p className="text-muted-foreground">
                    These Terms constitute the entire agreement between you and PredLabs regarding your 
                    use of the Service and supersede all prior and contemporaneous understandings, 
                    agreements, representations, and warranties.
                  </p>
                </div>
              </div>
            </section>

            {/* Final Acknowledgment */}
            <section className="border-t pt-8 mt-8">
              <div className="bg-primary/5 border border-primary/20 rounded-lg p-6">
                <h3 className="text-lg font-semibold mb-4 text-primary">Acknowledgment</h3>
                <p className="text-muted-foreground">
                  BY CLICKING "I AGREE" OR BY USING THIS SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE 
                  TERMS AND CONDITIONS, UNDERSTAND THEM, AND AGREE TO BE BOUND BY THEM. YOU FURTHER ACKNOWLEDGE 
                  THAT THIS SERVICE IS FOR INFORMATIONAL PURPOSES ONLY, THAT IT IS NOT A SUBSTITUTE FOR 
                  PROFESSIONAL MEDICAL ADVICE, AND THAT ITS OUTPUTS CANNOT BE USED FOR ANY MEDICOLEGAL PURPOSE.
                </p>
              </div>
            </section>

            {/* Contact */}
            <section className="text-center text-sm text-muted-foreground pt-4">
              <p>
                If you have any questions about these Terms, please contact us at{' '}
                <a href="mailto:support@predlabs.com" className="text-primary hover:underline">
                  support@predlabs.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
