// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opvssqukuyemcxgoflzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wdnNzcXVrdXllbWN4Z29mbHp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDcxNDQsImV4cCI6MjA3MjIyMzE0NH0.Cwj3Xynu8Yg1RkuoN7YjMgRZVDPONRKYD5JIStLn6KU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});